### ISSUE TITLE
Brunch

### ISSUE THREAD

**Issue by KNesvit** [AliveMath/Buyko-Master-Degree#1]
@abuyko когда вы желаете что-то делать над Вашим дипломом, вы создаете brunch = имя что вы делаете и постепенно создаете там commits. Когда считаете нужным показать и добавить в master вы делаете pull request c описанием изменений. Если возникают вопросы вы создаете мероприятие в календаре и отправляете мне инвайт. Учитесь пользоваться GitHub ) и научитесь обрамлять в необходимые слова то, что вы делаете. Имя нынешнего вашего файла кода в Jupyter мало характеризует то, что вы там делаете.

**Comment by abuyko** [comment]
хорошо, я учту :)
